name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.0', '3.1', '3.2' ]
        rails: [ '6.1', '7.0' ]

    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile-activemodel-${{ matrix.rails }}.x

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # 'bundle install' and cache gems

    - name: RSpec
      run: bundle exec rake
